### PR TITLE
add tickComponent prop and use @vx/text for axis ticks

### PR DESCRIPTION
**Pull request by sto3psl**
#### :boom: Breaking Changes

None 🎉 

#### :rocket: Enhancements

Implements features mentioned in #259 

- use `@vx/text` for axis ticks and axis label
- add `tickComponent` prop to all axis components

#### :memo: Documentation

1. By default `<Axis />` components now use `@vx/text` to render tick labels. This enables multi line labels and scaling text to fit in a certain amount of space.

Example:
```jsx
<Axis 
  {...axisProps}
  tickLabelProps = (tickValue, index) => ({
    textAnchor: 'middle',
    verticalAnchor: 'middle',
    width: 100,
    scaleToFit: true
  })
/>
```

2. `<Axis />` components got a new prop `tickComponent` to enable rendering of custom ticks. With this prop one can completely customize ticks without having to create a new custom `<Axis />` component.

Example:
```jsx
<Axis
  {...axisProps}
  tickComponent={({ x, y, formattedValue }) => (
    <g>
      <circle cx={x} cy={y} r={2} fill='rebeccapurple' />
      <text x={x + 4} y={y}>{formattedValue}</text>
    </g>
  )}
/>
```

`tickComponent` accepts a function and gets called with the following attribute:
```js
tickComponent({ x, y, formattedValue, ...tickLabelPropsObj })
```

---

P.S.: I think currently it's quite hard to get started developing on `vx`. I don't really know how lerna works and if I maybe did something wrong, please let me know. A little __Getting started developing vx__ section in the readme would be lovely.

### CODE REVIEW

**Comment by williaster** [comment]
this will be a great addition @sto3psl! 🚀 

and good suggestion about the dev environment instructions, I just [added a section to the readme](https://github.com/hshoff/vx#development) about this.

**Comment by techniq** [comment]
Nice work!

And thanks Chris for adding the dev notes. I've always kept a note in my
wiki (https://github.com/techniq/wiki/wiki/vx) as I have to reremember.
Now I won't have to 😁.

**Comment by sto3psl** [comment]
Great I did almost everything correctly forking vx and getting started 😄. Thank you @williaster for the quick addition!

**Comment by hshoff** [comment]
LGTM thanks for the contribution @sto3psl!

**Pull request merged**
