### PR TITLE
[zoom] add @vx/zoom

### PR DESCRIPTION
**Pull request by hshoff**
WIP

fixes: https://github.com/hshoff/vx/issues/7

vx-zoom

### CODE REVIEW

**Comment by hshoff** [comment]
Not ready for primetime yet, but here's a playground if you want to try it out: https://vx-demo.now.sh/transform-playground

**Comment by hshoff** [comment]
Closing this in favor of a vx interactions branch WIP i've got going.

progress update
vx-ix

**Comment by mzabriskie** [comment]
Any update on zoom/interaction progress?

**Comment by techniq** [comment]
@mzabriskie you might be interested in the codesandbox linked in https://github.com/hshoff/vx/issues/244. I have plans to PR something similar to vx once @vx/brush is merged and work through more use cases listed in the issue.

**Comment by hshoff** [comment]
@mzabriskie coming soon! focused on the new build at the moment (https://github.com/hshoff/vx/pull/298), will finish up the final polish on interactions and get them out afterwards

**Pull request closed without merging**
