### PR TITLE
add diagonal right to left pattern

### PR DESCRIPTION
**Pull request by dennisja**
#### :rocket: Enhancements

- Add diagobalRightToLeft orientation

Fixes https://github.com/hshoff/vx/issues/723

### Screenshots
Screenshot 2020-06-17 at 08 49 50
Screenshot 2020-06-17 at 08 49 57

### CODE REVIEW

**Comment by dennisja** [comment]
@williaster I was thinking of adding a multi-select in the [boxplot example](https://github.com/hshoff/vx/blob/master/packages/vx-demo/src/sandboxes/vx-stats/Example.tsx) to enable one to select the pattern to show on the violin plot. What do you think about the Idea?

**Comment by williaster** [comment]
thanks for the addition @dennisja! could you add a screenshot of it working (maybe a comparison to the other diagonal to see feature parity)?

**Comment by dennisja** [comment]
> thanks for the addition @dennisja! could you add a screenshot of it working (maybe a comparison to the other diagonal to see feature parity)?

WDYT of adding a select in the boxplot example where one can choose the pattern to show?

**Comment by williaster** [comment]
@dennisja that sounds good, or alternatively could add to the `Pattern` example demo?

**Comment by dennisja** [comment]
@williaster Adding it to the Pattern example sounds and looks better. It is what I have gone with

**Comment by dennisja** [comment]
@williaster I noticed that the build is failing because of some types that are not related to the pull request. I don't know whether it will be a good idea fixing them in this PR for the build to pass. Is can we add an issue to fix them or should I go ahead and fix them in this PR?

**Comment by hshoff** [comment]
@dennisja could you rebase your branch from upstream and push? the fix landed in https://github.com/hshoff/vx/pull/751

- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Pull request merged**
